# Generated by Django 4.2.3 on 2023-08-05 07:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, upload_to=api.models.user_directory_path),
        ),
    ]
