# Generated by Django 4.2.3 on 2023-07-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('disk_space', models.IntegerField(default=30720)),
                ('used_space', models.IntegerField(default=0)),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
