# Generated by Django 4.2.3 on 2023-07-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'User already exist bliat'}, max_length=100, unique=True),
        ),
    ]
